baseURL = "https://filip-dobrocky.github.io/"
languageCode = "en-us"
title = "Filip Dobrocky"
theme = "cactus"
copyright = "Filip Dobrocky" # cactus will use title if copyright is not set
disqusShortname = "FDobrocky" # Used when comments is enabled. Cactus will use site title if not set

[services]
  [services.googleAnalytics]
    ID = 'G-DKYR6BSRDK'



# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Works"
url = "/works"
weight = 2

[[menu.main]]
name = "Events"
url = "/events"
weight = 3

[[menu.main]]
name = "Music"
url = "/#projects"
weight = 4

[[menu.main]]
name = "Code"
url = "/code"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  showAllPostsArchive = false # default

  # Home page settings
  description = "Sound designer / programmer / audio engineer / multimedia artist."
  mainSection = "works" # your main section
  mainSectionTitle = "Works"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  musicUrl = "https://filipdobrocky.bandcamp.com/"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006" # default

  # Post page settings
  show_updated = false # default
  showReadTime = false # default

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "bandcamp"
    link = "https://filipdobrocky.bandcamp.com/"
  [[params.social]]
    name = "github"
    link = "https://github.com/filip-dobrocky"
  [[params.social]]
    name = "strava"
    link = "https://www.strava.com/athletes/24192923"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/filip-dobrocky/"
