name: Build CV PDF

on:
  push:
    branches:
      - main

jobs:
  build-cv:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install md2pdf

      - name: Run cv-generator.py
        working-directory: cv-generator
        run: |
          python cv-generator.py

      - name: Move CV PDF to static/cv
        run: |
          mkdir -p static/cv
          mv cv-generator/cv.pdf static/cv/FilipDobrockyCV.pdf

      - name: Set up authentication
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push CV PDF
        run: |
          git add static/cv/FilipDobrockyCV.pdf
          git commit -m 'Update CV PDF [auto]' || echo "No changes to commit"
          git push
