name: Build CV PDF

on:
  push:
    branches:
      - main

jobs:
  build-cv:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install md2pdf

      - name: Run cv-generator.py
        working-directory: cv-generator
        run: |
          python cv-generator.py

      - name: Move CV PDF to public/cv
        run: |
          mkdir -p public/cv
          mv cv-generator/cv.pdf public/cv/FilipDobrockyCV.pdf

      - name: Commit and push CV PDF
        run: |
          git add public/cv/FilipDobrockyCV.pdf
          git commit -m 'Update CV PDF [auto]' || echo "No changes to commit"
          git push
